### ISSUE TITLE
BuildOne Bounty: Dual Active Serial Ports

### ISSUE THREAD

**Issue by ekettenburg** [digistump/BuildOne#1]
**Dual Active Serial Ports** - currently you would need to reflash the firmware to switch between TX0/RX0 aka USB and the TX2/RX2 pins we are using for WiFi. We believe a much better user experience would be to have both ports active at the same time so either can be used. Similar to BLUETOOTH_SERIAL in the Repetier firmware.

**Bounty:** $100 cash / $200 credit towards adding to your order

**Terms:**

If you are sure you can do this, and able to do this quickly - please feel free to respond to this issue and say that you are working on it and when you will complete it, so that others don't waste their time on it. If you are just entertaining the idea/unsure if you can do it, please don't "claim" it until you are sure.

Cash or credit is your choice. Cash to be paid via Paypal. Credit will be applied to your BuildOne order for additional items, it cannot be refunded to cash and other items cannot be refunded to cash and then credit used to pay for them.

You may credit yourself in the files as well, leaving in tact existing licenses and credits.

Legal Stuff: We will choose a winner at our sole discretion. The winner will be the first pull request/issue update/etc that submits fully working code meeting the above requirements and following good coding practices, based on the timestamp of the pull request. If the pull request is to an existing software project the winner will be expected to follow through and make the best effort to get it merged. Cash awards will be made in USD. This is not an offer for hire. All work submitted becomes the property of Digistump LLC/Robotic Industries LLC to be used at our discretion in compliance with any associated licenses. Void where prohibited by law.

**Comment by the-real-orca** [comment]
I looked at the Marlin code, and it would be possible read commands from two serial inputs. Beside the basic data input there needs to be simple mechanism to make sure that data from different sources do not interfere with each other. (e.g. processing half a command from Serial 0 and the rest of the line from Serial 2.) But that shouldn't be too difficult either.

I’m going to start with it tomorrow. For coding and basic testing I would estimate about three week(ends).

Some questions:
1) What is the targeted Marlin version 1.1.x (ATmega based) or 2.0.x (32bit)?
2) What type of mainmoard is the BuildOne based on? What configuration should I use for testing?

**Comment by ekettenburg** [comment]
Great - thanks for giving this a go!

1. Marlin 1.1.x
2. A RAMPS or similar board is a pretty close match and close enough to be an exact match for this.

**Comment by the-real-orca** [comment]
The first version of the dual serial post patch is ready:
https://github.com/the-real-orca/Marlin/tree/Dual_Serial_Ports

Simply enable the **SEC_SERIAL_PORT** setting in _Configruation.h_

You can switch between the two ports on the fly (without any jumpers, re-flashing, etc.). However you must to take care not to interfere with the other serial port while printing. That means: it’s totally fine to have both ports connected and send commands from either of the ports. It’s guaranteed that each single command will be handled correctly and no “half”-command line will be processed. However, if you try to start two prints in parallel the two ports will fight against each other and the result will be a big mess, obviously.
I have tested it by printing a Benchy with the primary port. After finishing this print, I switched the host SW to the secondary port and printed another Benchy without changing anything else.

**Comment by ekettenburg** [comment]
@the-real-orca Awesome - thank you, the level of interference allowed sounds perfect since we want the ESP8266 to be able to query the status even if printed by USB, but it is reasonable to expect someone not to try to print from both at once - we can even lock this out potentially in our version of Cura/the cloud.

Would you mind seeing if the Marlin project would like to pull this?

**Comment by the-real-orca** [comment]
I already submitted a pull request (https://github.com/MarlinFirmware/Marlin/pull/10438), however Marlin 1.1.x has a feature stop, and the next 1.1.9 release will be bugfixes only. All the new development is going to version 2.0. Marlin 2.0 has already some kind of dual serial port integrated, however I have not looked into it.

Would be interesting to have some feedback how the serial patch is working on the BuildOne.

**Comment by ekettenburg** [comment]
That's right - thanks for submitting it any way though! 

As mentioned in the other issue - please email me at support@digistump.com to claim your bounty for both this and the pass through mode.

Closing this - will reopen if I find any issues in testing, but so far it is testing well!

Thanks!
