### ISSUE TITLE
BuildOne Bounties: Laser Integration

### ISSUE THREAD

**Issue by ekettenburg** [digistump/BuildOne#3]
**Laser Integration** - The laser engraver add-on will ship with LaserWeb as the recommended software. The Laser is controlled by PH6/D9. Up until now we have treated that pin as a Fan and used the Fan Gcodes to control the laser intensity. (Marlin has since added M3/M4 laser/spindle control that should also work for this) This allows it to work with LaserWeb with vector but not with raster without some post processing. Raster mode expects laser of on G1 and off on G0 with S to set intensity.  Either this needs to be added to Marlin or the makers of LaserWeb to need to be convinced to allow a pull (and the pull created) to support the current Marlin laser methods.

References: https://github.com/MarlinFirmware/Marlin/issues/9893, https://github.com/MarlinFirmware/Marlin/commit/55a87da036c48559fabd20246d9b810a3c93b0fe, https://github.com/LaserWeb/LaserWeb4/issues/395, https://www.v1engineering.com/forum/topic/laserweb-with-standard-marlin/

**Bounty:** $200 cash / $400 credit towards adding to your order

**Terms:**

If you are sure you can do this, and able to do this quickly - please feel free to respond to this issue and say that you are working on it and when you will complete it, so that others don't waste their time on it. If you are just entertaining the idea/unsure if you can do it, please don't "claim" it until you are sure.

Cash or credit is your choice. Cash to be paid via Paypal. Credit will be applied to your BuildOne order for additional items, it cannot be refunded to cash and other items cannot be refunded to cash and then credit used to pay for them.

You may credit yourself in the files as well, leaving in tact existing licenses and credits.

Legal Stuff: We will choose a winner at our sole discretion. The winner will be the first pull request/issue update/etc that submits fully working code meeting the above requirements and following good coding practices, based on the timestamp of the pull request. If the pull request is to an existing software project the winner will be expected to follow through and make the best effort to get it merged. Cash awards will be made in USD. This is not an offer for hire. All work submitted becomes the property of Digistump LLC/Robotic Industries LLC to be used at our discretion in compliance with any associated licenses. Void where prohibited by law.

**Comment by rmcolbert** [comment]
LaserWeb does accept pull requests to their dev repo. 
[https://github.com/LaserWeb/LaserWeb4/wiki/How-to-Contribute](https://github.com/LaserWeb/LaserWeb4/wiki/How-to-Contribute)

**Comment by zachwelch** [comment]
A patch to fix the issue reported in https://github.com/LaserWeb/LaserWeb4/issues/395 has been merged (https://github.com/LaserWeb/LaserWeb4/pull/473), thus rendering this bounty moot.

**Comment by ekettenburg** [comment]
Thanks @zachwelch for letting us know! That's awesome!

Closing.
